name: Teleport Application Proxy
author: Gravitational, Inc.
description: Opens a local HTTP proxy server in the background of your workflow that can be used to access HTTP apps available in Teleport.
inputs:
    anonymous-telemetry:
        description: Enables anonymous telemetry. See https://goteleport.com/docs/machine-id/reference/telemetry/ for more information.
        required: false
    ca-pins:
        description: Specifies one or more trusted CAs to initially validate the identity of the Auth Server when connecting directly to it. This is not required for Teleport Cloud or when connecting via a Teleport Proxy
        required: false
    certificate-ttl:
        description: Specify the length that the generated credentials should be valid for. Defaults to "1h"
        required: false
    diag-port:
        description: Specify an alternative port for the diagnostics service.
        required: false
        default: "57263"
    disable-env-vars:
        description: Disables the automatic setting of environment variables like`TELEPORT_IDENTITY_FILE` by the action. This can be useful in more complex workflows where multiple identities are being used.
        required: false
    listen:
        description: Specify a listener URI for the local tunnel, e.g. tcp://localhost:1234
        required: true
    proxy:
        description: Specify the address of your Teleport Proxy.
        required: true
    timeout-ms:
        description: The maximum amount of time to wait in milliseconds for the tunnel to become ready. Set to 0 to skip waiting.
        required: false
        default: "30000"
    token:
        description: Specify the Teleport token to use to join.
        required: true
runs:
    using: node20
    main: dist/main/index.js
    post: dist/post/index.js
branding:
    color: purple
    icon: terminal
